version: "0.0.1"
services:
  mongo:
    container_name: mongo
    dockerfile: "Dockerfile.db"
    build: .
  server:
    container_name: server
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
    dockerfile: "Dockerfile.server"
    restart: always
  client:
    container_name: client
    build: .
    ports:
      - "3000:3000"
    dockerfile: "Dockerfile.client"