version: "0.0.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo